### ISSUE TITLE
Ticker returning all available pairs

### ISSUE THREAD

**Issue by DanielFragaBR** [viabtc/viabtc_exchange_cn_api_en#2]
Is it possible to implement a ticker call returning all pairs available? For example:

https://www.viabtc.cn/api/v1/market/ticker

This would return the tickers for btccny, ethcny, zeccny and all future pairs (instead of forcing us to get one by one).

Thanks.

**Comment by buyongji** [comment]
the url return all pairs available:https://www.viabtc.com/api/v1/market/ticker/all
